FROM nginx:mainline-alpine

# Copying everything to the container
COPY client /usr/app/

# Setting WORKDIR
WORKDIR /usr/app/

RUN rm /etc/nginx/conf.d/*
RUN pwd
RUN ls

COPY ./helloworld.conf /etc/nginx/conf.d/
COPY ./index.html /usr/share/nginx/html/
